server:
  port: 8080
  servlet:
    context-path: /

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booknovels?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123


  thymeleaf:
    encoding: UTF-8



mybatis:
  mapperLocations: classpath:mapper/*.xml

  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.cduestc.book_novels.mapper: DEBUG
  #包名下的 bean取别名
  type-aliases-package: com.cduestc.book_novels.bean

pagehelper:
  helper-dialect: mysql
  reasonable: true
#  分页是否合理
  support-methods-arguments: true

